apiVersion: v1
kind: ReplicationController
metadata:
  name: shiny-server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: shiny-server
    spec:
      containers:
      - name: shiny-server
        image: markedmondson1234/shiny-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3838
      restartPolicy: Always
